### ISSUE TITLE
Module parse failed: Unexpected character '@' - You may need an appropriate loader to handle this file type.

### ISSUE THREAD

**Issue by edoubart** [amitai10/rails-angular-webpacker#1]
Good evening, 

I tried to follow your "Angular 2 with Rails and Webpacker" blog post and ran into the following error:

```
ERROR in ./app/javascript/hello_angular/app/app.module.ts
Module parse failed: Unexpected character '@' (7:0)
You may need an appropriate loader to handle this file type.
| import { AppComponent } from './app.component';
|
| @NgModule({
|   declarations: [
|     AppComponent
 @ ./app/javascript/hello_angular/index.ts 4:0-45
 @ ./app/javascript/packs/hello_angular.js
 @ multi (webpack)-dev-server/client?http://localhost:3035 ./app/javascript/packs/hello_angular.js
webpack: Failed to compile.
```

After cloning your repository, running `bundle install`, `yarn install` and attempting a `bin/webpack-dev-server`, I encountered the same error as above.

Any clue?

Thank you

**Comment by edoubart** [comment]
It looks like the file-structure has changed a little bit. There is a new `config/webpack/loaders/` directory with a `typescript.js` file in it.

**Comment by amitai10** [comment]
@edoubart thanks, I will update the post

**Comment by edoubart** [comment]
Awesome, thank you @amitai10 !
